### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by vlauciani** [italia/spid-keycloak-provider#45]
Buongiorno

Durante la fase di compilazione del package, nel sezione TESTS, ottengo:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.keycloak.broker.spid.metadata.SpidSpMetadataResourceProviderTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Nov 16, 2022 5:11:08 PM org.keycloak.broker.spid.metadata.SpidSpMetadataResourceProvider get
WARN: Failed to export SAML SP Metadata!
java.lang.Exception: No SPID providers found!
	at org.keycloak.broker.spid.metadata.SpidSpMetadataResourceProvider.get(SpidSpMetadataResourceProvider.java:107)
	at org.keycloak.broker.spid.metadata.SpidSpMetadataResourceProvider$MockitoMock$566452705.get$accessor$iFOSaukb(Unknown Source)
	at org.keycloak.broker.spid.metadata.SpidSpMetadataResourceProvider$MockitoMock$566452705$auxiliary$qnZMIw1L.call(Unknown Source)
	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
. . .
```

mi chiedevo se fosse normale, visto che l'ho trovato anche nell'ultima *Action*:
- https://github.com/italia/spid-keycloak-provider/actions/runs/3393472301/jobs/5656103831#step:5:484

Grazie.

**Comment by nicolabeghin** [comment]
Chiudo in quanto vecchio di 2 anni ormai
