### ISSUE TITLE
Problema di signature con flow tra spid-saml-check e spid-keycloak-provider

### ISSUE THREAD

**Issue by gabrielesilinic** [italia/spid-keycloak-provider#67]
![image](https://github.com/italia/spid-keycloak-provider/assets/51238829/59d7971b-54d4-4b8b-82df-29bda0479681)

Sono estremamente vicino ad ottenere qualcosa di funzionante, ma per qualche ragione qualche certificato non esiste e non mi è chiaro cosa voglia.

qui quello di cui keycloak si lamenta

```
 2024-06-14 14:34:57,974 ERROR [org.keycloak.broker.spid.SpidSAMLEndpoint] (executor-thread-240) validation failed: org.keycloak.common.VerificationException: Invalid signature on document
spid-keycloak-1    |    at org.keycloak.protocol.saml.SamlProtocolUtils.verifyDocumentSignature(SamlProtocolUtils.java:96)
spid-keycloak-1    |    at org.keycloak.broker.spid.SpidSAMLEndpoint$PostBinding.verifySignature(SpidSAMLEndpoint.java:763)
spid-keycloak-1    |    at org.keycloak.broker.spid.SpidSAMLEndpoint$Binding.handleSamlResponse(SpidSAMLEndpoint.java:695)
spid-keycloak-1    |    at org.keycloak.broker.spid.SpidSAMLEndpoint$Binding.execute(SpidSAMLEndpoint.java:293)
spid-keycloak-1    |    at org.keycloak.broker.spid.SpidSAMLEndpoint.postBinding(SpidSAMLEndpoint.java:204)
spid-keycloak-1    |    at org.keycloak.broker.spid.SpidSAMLEndpoint$quarkusrestinvoker$postBinding_e2ae3e4e98121b36952f2279cd4bb60100612099.invoke(Unknown Source)
spid-keycloak-1    |    at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
spid-keycloak-1    |    at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
spid-keycloak-1    |    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
spid-keycloak-1    |    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
spid-keycloak-1    |    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
spid-keycloak-1    |    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
spid-keycloak-1    |    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
spid-keycloak-1    |    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
spid-keycloak-1    |    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
spid-keycloak-1    |    at java.base/java.lang.Thread.run(Thread.java:840)
spid-keycloak-1    |
spid-keycloak-1    | 2024-06-14 14:34:57,974 WARN  [org.keycloak.events] (executor-thread-240) type="IDENTITY_PROVIDER_RESPONSE_ERROR", realmId="9b6a774a-c8f9-49ab-af42-f6bd72af4b65", clientId="null", userId="null", ipAddress="0:0:0:0:0:0:0:1", error="invalid_signature"
```

dove potrei andare a guardare per capire che sta succedendo? il validator dice che è tutto a posto e il flow va tutto fino a che non ritorna a keycloak, tutto è in localhost, keycloak è sotto keycloak.localhost nello specifico, il provider spid-saml-check è sotto https (non certificato correttamente però, clicco trust ogni volta, non so che farci, sono in localhost)

qui la config delle parti importanti

![image](https://github.com/italia/spid-keycloak-provider/assets/51238829/5798c5f0-f445-483d-ab94-8d9df6230de9)

![image](https://github.com/italia/spid-keycloak-provider/assets/51238829/ccb74325-04e7-499a-ab88-f09ce96310d9)

**Comment by nicolabeghin** [comment]
@gabrielesilinic hai provato a configurare l'IdP configurandolo col tool https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client e non manualmente? ci sono una miriade di parametri e andare in delta è ardua!

**Comment by gabrielesilinic** [comment]
> @gabrielesilinic hai provato a configurare l'IdP configurandolo col tool https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client e non manualmente? ci sono una miriade di parametri e andare in delta è ardua!

Ho provato, ma non riesce a comunicare correttamente con keycloak (tutto locale). il motivo non è chiaro, ma sembra abbia difficultà ad autenticarsi nonostante mi sembra di averlo configurato correttamente.

**Comment by nicolabeghin** [comment]
> > @gabrielesilinic hai provato a configurare l'IdP configurandolo col tool https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client e non manualmente? ci sono una miriade di parametri e andare in delta è ardua!
> 
> Ho provato, ma non riesce a comunicare correttamente con keycloak (tutto locale). il motivo non è chiaro, ma sembra abbia difficultà ad autenticarsi nonostante mi sembra di averlo configurato correttamente.

ma la chiamata a keycloak con cosa la fai?

**Comment by alcad** [comment]
> > @gabrielesilinic hai provato a configurare l'IdP configurandolo col tool https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client e non manualmente? ci sono una miriade di parametri e andare in delta è ardua!
> 
> Ho provato, ma non riesce a comunicare correttamente con keycloak (tutto locale). il motivo non è chiaro, ma sembra abbia difficultà ad autenticarsi nonostante mi sembra di averlo configurato correttamente.

Sono incappato nello stesso problema e ho risolto con una patch alla codebase.

La trovi in questo commit:

https://github.com/italia/spid-keycloak-provider/commit/10e5cba7a45bd26bc65e3b6e2c11afffc973c58a

**Comment by nicolabeghin** [comment]
> Sono incappato nello stesso problema e ho risolto con una patch alla codebase.
> 
> La trovi in questo commit:
> 
> [10e5cba](https://github.com/italia/spid-keycloak-provider/commit/10e5cba7a45bd26bc65e3b6e2c11afffc973c58a)

@alcad potresti sottomettere una PR così da condividere il fix con tutti? grazie!

**Comment by ktsw89** [comment]
Salve a tutti, sono incappato nel medesimo errore, a differenza del primo post ho installato keycloak su un server remoto ed utilizzo l'Idp dell'ambiente demo di spid (https://demo.spid.gov.it/).

Anche in questo caso la configurazione è uguale a quella proposta, va tutto liscio fino al ritorno su keycloak.


```
2025-03-14 14:32:26,299 ERROR [org.keycloak.broker.spid.SpidSAMLEndpoint] (executor-thread-95) validation failed: org.keycloak.common.VerificationException: Invalid signature on document
	at org.keycloak.protocol.saml.SamlProtocolUtils.verifyDocumentSignature(SamlProtocolUtils.java:97)
	at org.keycloak.broker.spid.SpidSAMLEndpoint$PostBinding.verifySignature(SpidSAMLEndpoint.java:758)
	at org.keycloak.broker.spid.SpidSAMLEndpoint$Binding.handleSamlResponse(SpidSAMLEndpoint.java:690)
	at org.keycloak.broker.spid.SpidSAMLEndpoint$Binding.execute(SpidSAMLEndpoint.java:290)
	at org.keycloak.broker.spid.SpidSAMLEndpoint.postBinding(SpidSAMLEndpoint.java:201)
	at org.keycloak.broker.spid.SpidSAMLEndpoint$quarkusrestinvoker$postBinding_e2ae3e4e98121b36952f2279cd4bb60100612099.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

2025-03-14 14:32:26,300 WARN  [org.keycloak.events] (executor-thread-95) type="IDENTITY_PROVIDER_RESPONSE_ERROR", realmId="462f116f-f33d-4f37-a10a-558e5e380876", realmName="SPID", clientId="null", userId="null", ipAddress="127.0.0.1", error="invalid_signature"
```

<img width="700" alt="Image" src="https://github.com/user-attachments/assets/560c6a28-7168-4e5f-ab1f-9d92fde8e440" />

<img width="700" alt="Image" src="https://github.com/user-attachments/assets/446f65a8-e57b-4da4-ac91-509825ba83a9" />

**Comment by nicolabeghin** [comment]
> va tutto liscio fino al ritorno su keycloak.

Di solito sotto allo stacktrace generico c'è quello esteso che fornisce maggiori info sul motivo del fallimento della validazione della firma (es con spid-sp-test falliva perché non viene passato il certificato nella response). Senza di ciò diventa difficile qualsiasi analisi.

In ogni caso essendo in localhost non capisco come tu possa usare il Demo dato che il primo step è passargli il link del metadata che deve essere raggiungibile da internet pubblico affinché il Demo possa recuperarlo e costruirne da esso la risposta firmata. In altri termini, andrei per step verificando come prima cosa tutti i check sul metadata.

Per il resto il Demo confermo che lo usiamo quasi giornalmente con il plugin quindi dovrebbe funzionarti.

**Comment by ktsw89** [comment]
Ciao Nicola, in primis grazie della risposta. Non sono in remoto, ho installato keycloak su un server esterno. Dopo varie prove fatte nel fine settimana sono riuscito a far funzionare la soluzione. Il problema risiedeva nel certificato x509: non avevo inserito il valore pensando che lo recuperasse automaticamente dai metadata attraverso il campo metadata descriptor url.

**Comment by nicolabeghin** [comment]
> Il problema risiedeva nel certificato x509: non avevo inserito il valore pensando che lo recuperasse automaticamente dai metadata attraverso il campo metadata descriptor url

ottimo, bene così!
