### ISSUE TITLE
Problema import metadati idp

### ISSUE THREAD

**Issue by matteo1294k** [italia/spid-keycloak-provider#77]
Salve, sto utilizzando la versione più recente di keycloak e dello spiIdentity priveder. 
L'installazione è avvenuta correttamente.
Seguendo la documentazione per il processo di configurazione, sono arrivato a un punto in cui indica di importare da file i metadata dei providers.

Il probelma è che in questa versione di keycloak non è presente il tasto per l'inport e non risulta disponibile il vecchio tema.

Avete delle dritte?
grazie

**Comment by nicolabeghin** [comment]
> Il probelma è che in questa versione di keycloak non è presente il tasto per l'inport e non risulta disponibile il vecchio tema.

Consiglio vivamente di utilizzare il client di configurazione https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client perchè ci sono n-mila altre opzioni da impostare e fare a mano è al limite del disumano!

**Comment by matteo1294k** [comment]
@nicolabeghin ho provato a usare il configuratore che mi hai suggerito ma risulta non funzionante. provando a usarlo ottengo il seguente errore:

2025-01-23 11:31:49 /usr/src/node_modules/rxjs/internal/util/hostReportError.js:4
2025-01-23 11:31:49     setTimeout(function () { throw err; }, 0);
2025-01-23 11:31:49                              ^
2025-01-23 11:31:49 
2025-01-23 11:31:49 TypeError: Cannot read properties of undefined (reading 'data')
2025-01-23 11:31:49     at MergeMapSubscriber.project (/usr/src/app/createidps.js:20:58)
2025-01-23 11:31:49     at MergeMapSubscriber._tryNext (/usr/src/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
2025-01-23 11:31:49     at MergeMapSubscriber._next (/usr/src/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
2025-01-23 11:31:49     at Subscriber.next (/usr/src/node_modules/rxjs/internal/Subscriber.js:66:18)
2025-01-23 11:31:49     at /usr/src/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
2025-01-23 11:31:49     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-01-23 11:31:49 
2025-01-23 11:31:49 Node.js v22.13.1

Inoltre ho visto che è stata aperta una issue direttamente sil configuratore: 

https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client/issues/10
